public enum EventDefine
{
    ShowGamePanel,
    DecidePath,
    AddScore,
    UpdateScoreUI,
    PlayerMove,
    AddDiamond,
    UpdateDiamondUI,
    ShowGameOverPanel,
    ShowShopPanel,
    ShowMainPanel,
    ChangeSkin,
    ShowHint,
    ShowResetPanel,
    ShowRankPanel,
    PlayClickAudio,
    IsMusicOn
}
